### ISSUE TITLE
Fix YouTube style 

### ISSUE THREAD

**Issue by loikein** [loikein/hugo-tufte#6]
Also I want to try the native CSS video ratio thing again (if it was not my hallucination).

Future me: you're welcome.

**Comment by loikein** [comment]
Found the new ratio thing: [Embed responsive YouTube videos in 2021 - DEV Community](https://dev.to/deammer/embed-responsive-youtube-videos-in-2021-5dkh)

```css
.video {
  aspect-ratio: 16 / 9;
  width: 100%;
}
```

Seems # of browsers with support for `@supports` is smaller than support for `aspect-ratio`.
